"""add visibility to notes and is_active to users

Revision ID: 959a20e0dea4
Revises: e6361fdb29d1
Create Date: 2026-06-14 03:58:58.265197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959a20e0dea4'
down_revision: Union[str, None] = 'e6361fdb29d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default fills existing rows before NOT NULL is enforced.
    # Without it, ALTER TABLE fails on any non-empty table.
    op.add_column('notes', sa.Column(
        'visibility', sa.String(length=10),
        nullable=False, server_default='private',
    ))
    op.add_column('users', sa.Column(
        'is_active', sa.Boolean(),
        nullable=False, server_default=sa.true(),
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('notes', 'visibility')
    # ### end Alembic commands ###
